import React from 'react';
import ReactDOM from 'react-dom';
import {Router, Route, IndexRoute, browserHistory} from 'react-router';
import App from './App';
import SongsList from './components/SongsList';
import SongDetails from './components/SongDetails';
import './index.css';

function Song(source, title, description, wiki,img,id) {
  this.url = source;
  this.displayText = title;
  this.description = description;
  this.wiki = wiki; //wikipidia
  this.Img = img;
  this.id = id;
}

const songs = [
  new Song('/Drake - Energy.mp3', 'Drake - Energy', 'This song finds Drake rapping about all the haters who try to drain him of his energy. Girls posting lies online, rival rap artists and associates he has to pretend that he likes, plus family issues are all obstacles that the MC has to deal with as his fame continues to rise.',`Release[edit]
  The video of "Energy" was released on Apple Music and users with iTunes and registered Apple Music account can watch this video.[3]

  Synopsis[edit]
  The music video for "Energy" features Drake transformed into several notable celebrities, including: television personality Oprah Winfrey, during her famous interview with Tom Cruise; professional boxer Floyd Mayweather, Jr.; singer Justin Bieber, from a Calvin Klein advertisement; singer Miley Cyrus, from her own music video for "Wrecking Ball"; former mayor of Toronto, Rob Ford, enjoying crack cocaine in an alley; entertainer Kanye West, during the filming of his own music video for "Bound 2"; United States President Barack Obama, during a presidential address; NBA player LeBron James; and O.J. Simpson, during the high speed car chase that led to his arrest. In each of these iterations, Drake mimes along with the song. Interspersed with these clips is monochromatic footage of Drake and his entourage; along with portraits of other caricatures. Bookending the video, a child version of Drake is seen in a field with other children, who act not unlike bullies towards him. At the end of the video, the young Drake stands solitary in the field, while another child (who has now been revealed to have Drake's adult face) points a toy gun at him.[4]

  Reception[edit]
  Many critics stated that Drake uses this video to mock Justin Bieber, Miley Cyrus, Kanye West and many other celebrities in the video.[4] However, each usage of a notable person is timed to emphasize a certain lyric within the song. None of the personalities parodied in the footage have publicly responded to the video for "Energy".[citation needed] Pitchfork Media named "Energy" the 12th best music video of 2015.`,'https://i.ytimg.com/vi/W0A2Uhgvgig/hqdefault.jpg' , 0),

  new Song('/Drake - Hotline Bling.mp3', 'Drake - Hotline Bling', '“Hotline Bling” is most likely about Drake’s old flame from Toronto, Nebby. She’s had an on and off relationship with the 6 God a few times, and her Instagram account is a constant reminder that she’s never home – always traveling to exotic places, and out wearing almost nothing.',`On October 4, 2015, Drake announced a music video for the track via his Instagram account.[9] The video was financed by Apple Inc., and released on October 19, 2015 via Apple Music under a timed exclusivity agreement.[10] The Director X-directed video was inspired by the work of American artist James Turrell.[11] X has stated that he hopes that the video inspires men to dance more.[12][13] The video features Dominican model Damaris Lopez who appears at the beginning of the video.[14][15]

  Rap-Up wrote that Drake "shows just how suave he can be with his moves" in this video.[12] Evan Minsker of Pitchfork called it a "pretty minimal clip".[16] The site also named "Hotline Bling" the seventh best music video of 2015.[17]

  The video, which has inspired many memes and parodies,[13][18] including a commercial from T-Mobile during Super Bowl 50 featuring Drake himself,[19] helped the song rise in chart position according to NME.[18] The song was parodied in the Saturday Night Live episode "Donald Trump/Sia", including where Trump himself starred in the parody.[20]

  As of February 2017, the music video has received over 1.13 billion views on YouTube,[21] and is the site's 34th most-watched video.[22]

  `, 'http://www.sohh.com/wp-content/uploads/Drake29.png', 1),

  new Song('/Drake - Take Care.mp3', 'Drake & Rihana - Take Care', 'The fifth song and title track from Take Care is, in effect, a sequel to “What’s My Name?” This track uses the beat and hook from the song “I’ll Take Care of U” from the Jamie XX and Gil Scott Heron album that dropped last year',`In 2010, Drake released his debut album Thank Me Later, continuing his creative partnership with record producer and audio engineer Noah "40" Shebib, who had first introduced his distinct sound on Drake's breakthrough mixtape So Far Gone (2009). Thank Me Later became a commercial success and was well received by music critics [6][8] and also [9] Prior to Take Care, Drake also expanded his repertoire as a live performer.[6] For the album, he intended to have Shebib handle most of the production and record a more cohesive sound than on Thank Me Later, which featured disparate production duties by Shebib and others.[10] In November 2010, Drake revealed the title of his next studio album will be Take Care.[11] In comparison to his debut album Drake revealed to Y.C Radio 1 that Thank Me Later was a rushed album, stating, "I didn’t get to take the time that I wanted to on that record. I rushed a lot of the songs and sonically I didn’t get to sit with the record and say, 'I should change this verse.' "Once it was done, it was done. That’s why my new album is called Take Care because I get to take my time this go-round." [12] Drake mentioned after OVO Fest 2011 that Take Care could have up to 18 songs on it, and added that Stevie Wonder contributed to the creative direction of the album and will be featured on the album as well. Drake also revealed that the album was recorded mainly in Toronto.[13] Debating whether to submit his final cut or not, Drake's preferred release date that motivated him to created a "Birthday edition", much like a deluxe edition to be released on the iTunes Store.[5]

Several producers were revealed to be working with Drake on Take Care other than Noah "40" Shebib (who is the main producer of the album), including T-Minus,[14] The xx's Jamie Smith[15] and Boi-1da (who is a long-time Drake collaborator).[16] He had initially recruited 9th Wonder for the album.[17] He even appeared on 9th's documentary The Wonder Year and expressed his desire to make a number one hit with him,[18] however, in an interview about a month prior to the slated release date, 9th said that he was not on the album.[19] 9th states that was a part of the reason, because he was going through an A&R and playing beats for them as opposed to the artist himself, which he is opposed to.[20] Drake had also been planning on having Q-Tip,[21] DJ Premier,[22] and The Neptunes[23] as producers on the album, but those projects fell through as well. Several artists were confirmed as collaborators with Drake on Take Care consist of Stevie Wonder, Kendrick Lamar, Chantal Kreviazuk,[24] André 3000, Rick Ross, Lil Wayne, Nicki Minaj and Rihanna.[25] He had initially reached out to Phonte of the former group Little Brother (who is a major influence on his career). The track was made for Take Care, but did not make it for the album, due to an issue he had with the producer. Drake admits in an interview to "dropping the ball" on the project and is optimistic about a future collaboration with Phonte.[26] He also wanted to collaborate with Justin Timberlake stating, "The song was gonna be dope," it was produced by Noah "40" Shebib. "It was solid, a solid little look. But he's so immersed in the acting thing, and I don't blame him, he's doing great at it. He was just like, 'I really want to work. I just can't do it right now. But we'll work as soon as I'm back in the studio.[27]

`,'http://static.djbooth.net/pics-tracks/drake-takecarevid.jpg' , 2),
  
  new Song('/Drake - Worst Behavior.mp3', 'Drake - Worst Behavior', 'In this track, Drake discusses the transition from a childhood without a father to the top rapper in the game. In the first verse, Drake claims “mothafuckas never loved us”, a stark contrast from later in the third verse, where he talks about his luxurious life and “tennis matches at the crib.”',`The song was met with generally positive reviews from music critics. Julia Leconte of NOW declared the song an album standout.[6] Jon Caramanica of The New York Times called the song, Nothing Was the Same's most chaotic and rowdy moment, "which seethes with spite."[7] Mike Diver of Clash said the song was the first song of the album "that really bumps, rather than grinding politely against the senses in the style that past Drake tracks like "Club Paradise" achieved. Drake sounds charged up, properly prickly, as he spits about how a certain “motherf*cker never loved us”."[8]

Adam Thomas of Sputnikmusic called "Worst Behavior" a club friendly trap glitch-out.[9] Jayson Greene of Pitchfork Media praised the production saying it featured, "glowering low-end synth and an insectile battery of defaced-sounding percussion." Also calling it the "meanest thing Drake has ever rapped over."[10] William Ketchum of HipHopDX also credited the song as, using "anthem choruses and punchline-laden verses to revel in victories despite humble beginnings." Along with praising the song's production.[11] Nathan Slavik of DJBooth spoke on the song saying, "once an album Drake likes to serve up a true banger, a track designed to be played at 11. On Take Care it was "Lord Knows" and on Nothing Was the Same it’s "Worst Behavior", a cut with a hypnotic beat but vocally doesn’t amount to much more than Drake quoting Mase and saying “motherfucker” as many times as possible; swearing seems to be the extent of his bad behavior. I get why Drizzy makes tracks like this, he clearly cares enough about his reputation as an emcee to defend it, but it’s also when he’s at his least convincing."[12]

Andrew Unterberger of PopCrush gave it a more negative review, saying "Worst Behavior" is definitely a low end for Nothing Was the Same, and like "Own It," it might have been a lot more effective coming later in the album, but coming where it does, it just sounds kinda brutal and unnecessary."[2] Jay Soul of RapReviews called the song, "interesting but arguably misplaced."[13]

Pitchfork Media named "Worst Behavior" the eighteenth best song of 2013. They elaborated saying, "Drake's worst has him flexing, ogling the zeroes on his checks, and defeating a handicapped Serena Williams on the tennis court. But "Worst Behavior" isn't so much about the what as much as the why—it's powered by a blinding sense of indignation that's spring-loaded for maximum comeuppance upon any and all who have ever doubted this middle-class Canadian child star. The song begins with what sounds like a flying saucer landing, as if the rapper rented a UFO from Area 51 and flew it to a poor old hater's backyard just so he could tell them to fuck off. Drake's Tourette's flow matches the beat's halting clatter, each incensed shout—remember?!... muhfucka?!—hitting like a bomb in the dark."[14] Kyle Kramer of Complex named it the third best song of 2013.`,'https://i.ytimg.com/vi/CccnAvfLPvE/maxresdefault.jpg' , 3),

  new Song('/Drake- One Dance.mp3', 'Drake - One Dance', '“One Dance” is an R&B song with dancehall and afrobeat inflections, featuring a slowed down sample of the vocals and chord stabs from a 2008 UK Funky house anthem, Kyla’s “Do You Mind,” produced by Crazy Cousinz.',`"One Dance" is a song by Canadian Toronto-based hip hop recording artist Drake from his fourth studio album, Views (2016). It features guest vocals from Nigerian Afrobeat artist Wizkid and British singer Kyla.[6] The artists co-wrote the dancehall and afrobeat song with its co-producers Nineteen85, DJ Maphorisa, and Noah "40" Shebib, with production assistance from Wizkid.[7][8] Crazy Cousinz and Kyla also received songwriting credits for the sampling of their 2008 UK funky song "Do You Mind".[9]

"One Dance" was released for digital download on April 5, 2016 and was serviced to US urban, rhythmic, and contemporary hit radio on April 12, 2016.[10][11][12] "One Dance" was released shortly after the release date for Views was announced, alongside "Pop Style". "One Dance" was the first of three dancehall singles to be released from Views, along with "Controlla" and "Too Good".[13][14] Critical response to "One Dance" was mostly positive, with critics praising the song's African and Caribbean sounds as well as its danceability.

"One Dance" reached number one in 15 different countries, including Australia, Canada, France, Germany, Ireland, the Netherlands, New Zealand, Switzerland, the United Kingdom, and the United States, becoming Drake's first number-one single in all 15 countries as the lead artist. It topped the US Billboard Hot 100 for 10 non-consecutive weeks and the UK Singles Chart for 15 consecutive weeks, making it the joint-second longest consecutive number one in the country. Drake had previously peaked at number-two on the US Billboard Hot 100 with "Best I Ever Had" (2009) and "Hotline Bling" (2015). Featured artist Wizkid became the first Nigerian artist to top the US Billboard Hot 100 chart.[15]

On September 7, 2016, Billboard named "One Dance" the 2016 Song of the Summer.[16] As of December 2016, it has sold 1.9 million copies in the US.[17] On October 15, 2016, "One Dance" became the most played song on streaming media service Spotify, with over one billion individual streams, overtaking the previous record held by Major Lazer and DJ Snake's "Lean On".[18][19][20] "One Dance" became the second dancehall song of 2016 to top the Billboard Hot 100 after Rihanna's "Work" which also featured Drake.`,'http://www.rap-up.com/app/uploads/2016/05/drake-views-2.jpg' , 4)

];


ReactDOM.render((
  <Router history={browserHistory}>
    <Route playlist={songs} path="/" component={App}>
      <IndexRoute songs={songs} component={SongsList} />
      <Route songs={songs} path="songs" component={SongsList} />
      <Route playlist={songs} path="songs/:id" component={SongDetails} />
    </Route>
  </Router>
),document.getElementById('root'));
